### ISSUE TITLE
char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.

### ISSUE THREAD

**Issue by kpcyrd** [rust-fuzz/cargo-fuzz#128]
I'm having trouble getting the fuzzer to work on aws with debian stretch. I can clone and fuzz the project correctly on archlinux, but for some reason if I clone the same repo and run the fuzzer on debian stable, the compile fails for really common crates, while some of them compile correctly. I've tried both cargo-fuzz 0.4.3 and 0.5.0. I've installed rust nightly with rustup (`nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.22.0-nightly (692b94ae2 2017-10-09)`).

```
# cargo fuzz run read_packet
   Compiling regex-syntax v0.4.1
       Fresh reduce v0.1.1
       Fresh unicode-xid v0.0.4
       Fresh lazy_static v0.2.9
       Fresh gcc v0.3.54
       Fresh matches v0.1.6
   Compiling strsim v0.6.0
   Compiling utf8-ranges v1.0.0
   Compiling byteorder v0.4.2
   Compiling cookie-factory v0.2.2
       Fresh quote v0.3.15
   Compiling ansi_term v0.9.0
   Compiling unicode-width v0.1.4
       Fresh cfg-if v0.1.2
       Fresh void v1.0.2
   Compiling arbitrary v0.1.0
       Fresh quick-error v1.2.1
   Compiling siphasher v0.2.2
   Compiling bitflags v0.9.1
   Compiling libc v0.2.31
       Fresh arrayref v0.3.4
   Compiling log v0.3.8
       Fresh vec_map v0.8.0
   Compiling serde v1.0.15
   Compiling num-traits v0.1.40
     Running `rustc --crate-name regex_syntax /root/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.4.1/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=2670ae5f089f9aeb -C extra-filename=-2670ae5f089f9aeb --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
     Running `rustc --crate-name strsim /root/.cargo/registry/src/github.com-1ecc6299db9ec823/strsim-0.6.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=b7e0359f222b5f26 -C extra-filename=-b7e0359f222b5f26 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
     Running `rustc --crate-name utf8_ranges /root/.cargo/registry/src/github.com-1ecc6299db9ec823/utf8-ranges-1.0.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=71219e9b4bee74ed -C extra-filename=-71219e9b4bee74ed --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
     Running `rustc --crate-name byteorder /root/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-0.4.2/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=268a34e1032ac5fc -C extra-filename=-268a34e1032ac5fc --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
     Running `rustc --crate-name cookie_factory /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-factory-0.2.2/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=e0941fe3ff68d20f -C extra-filename=-e0941fe3ff68d20f --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
     Running `rustc --crate-name siphasher /root/.cargo/registry/src/github.com-1ecc6299db9ec823/siphasher-0.2.2/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=8b6e9eca105cb84f -C extra-filename=-8b6e9eca105cb84f --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
       Fresh synom v0.11.3
       Fresh rand v0.3.16
     Running `rustc --crate-name unicode_width /root/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-width-0.1.4/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' -C metadata=03b45ee1e3213dd8 -C extra-filename=-03b45ee1e3213dd8 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
       Fresh unreachable v1.0.0
     Running `rustc --crate-name arbitrary /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arbitrary-0.1.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=e68d1b475408f834 -C extra-filename=-e68d1b475408f834 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
     Running `rustc --crate-name ansi_term /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.9.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=b2853dc15d9e48e6 -C extra-filename=-b2853dc15d9e48e6 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
     Running `rustc --crate-name bitflags /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-0.9.1/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="example_generated"' -C metadata=c0c799334b65e1a9 -C extra-filename=-c0c799334b65e1a9 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
       Fresh syn v0.11.11
       Fresh phf_generator v0.7.21
   Compiling thread_local v0.3.4
     Running `rustc --crate-name libc /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.31/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=edda134965c61f93 -C extra-filename=-edda134965c61f93 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
     Running `rustc --crate-name log /root/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.3.8/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=e616ac8e158c4bbb -C extra-filename=-e616ac8e158c4bbb --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
     Running `rustc --crate-name serde /root/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.15/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=677acf5414683fc0 -C extra-filename=-677acf5414683fc0 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
       Fresh serde_derive_internals v0.16.0
     Running `rustc --crate-name num_traits /root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.1.40/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=19204e4183bf2ab9 -C extra-filename=-19204e4183bf2ab9 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
       Fresh phf_codegen v0.7.21
       Fresh serde_derive v1.0.15
     Running `rustc --crate-name thread_local /root/.cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-0.3.4/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=983e8e1833d6113f -C extra-filename=-983e8e1833d6113f --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --extern lazy_static=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps/liblazy_static-6205bda4376e6dc3.rlib --extern unreachable=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps/libunreachable-8b04bf11cecbe370.rlib --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `unicode-width`.

Caused by:
  process didn't exit successfully: `rustc --crate-name unicode_width /root/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-width-0.1.4/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg feature="default" -C metadata=03b45ee1e3213dd8 -C extra-filename=-03b45ee1e3213dd8 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `bitflags`.

Caused by:
  process didn't exit successfully: `rustc --crate-name bitflags /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-0.9.1/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg feature="default" --cfg feature="example_generated" -C metadata=c0c799334b65e1a9 -C extra-filename=-c0c799334b65e1a9 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `cookie-factory`.

Caused by:
  process didn't exit successfully: `rustc --crate-name cookie_factory /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-factory-0.2.2/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=e0941fe3ff68d20f -C extra-filename=-e0941fe3ff68d20f --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `byteorder`.

Caused by:
  process didn't exit successfully: `rustc --crate-name byteorder /root/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-0.4.2/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=268a34e1032ac5fc -C extra-filename=-268a34e1032ac5fc --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `utf8-ranges`.

Caused by:
  process didn't exit successfully: `rustc --crate-name utf8_ranges /root/.cargo/registry/src/github.com-1ecc6299db9ec823/utf8-ranges-1.0.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=71219e9b4bee74ed -C extra-filename=-71219e9b4bee74ed --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `siphasher`.

Caused by:
  process didn't exit successfully: `rustc --crate-name siphasher /root/.cargo/registry/src/github.com-1ecc6299db9ec823/siphasher-0.2.2/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=8b6e9eca105cb84f -C extra-filename=-8b6e9eca105cb84f --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `thread_local`.

Caused by:
  process didn't exit successfully: `rustc --crate-name thread_local /root/.cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-0.3.4/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=983e8e1833d6113f -C extra-filename=-983e8e1833d6113f --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --extern lazy_static=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps/liblazy_static-6205bda4376e6dc3.rlib --extern unreachable=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps/libunreachable-8b04bf11cecbe370.rlib --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `strsim`.

Caused by:
  process didn't exit successfully: `rustc --crate-name strsim /root/.cargo/registry/src/github.com-1ecc6299db9ec823/strsim-0.6.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=b7e0359f222b5f26 -C extra-filename=-b7e0359f222b5f26 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `log`.

Caused by:
  process didn't exit successfully: `rustc --crate-name log /root/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.3.8/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg feature="default" --cfg feature="use_std" -C metadata=e616ac8e158c4bbb -C extra-filename=-e616ac8e158c4bbb --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
error: Could not compile `ansi_term`.

Caused by:
  process didn't exit successfully: `rustc --crate-name ansi_term /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.9.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=b2853dc15d9e48e6 -C extra-filename=-b2853dc15d9e48e6 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `libc`.

Caused by:
  process didn't exit successfully: `rustc --crate-name libc /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.31/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg feature="default" --cfg feature="use_std" -C metadata=edda134965c61f93 -C extra-filename=-edda134965c61f93 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `num-traits`.

Caused by:
  process didn't exit successfully: `rustc --crate-name num_traits /root/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.1.40/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=19204e4183bf2ab9 -C extra-filename=-19204e4183bf2ab9 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `regex-syntax`.

Caused by:
  process didn't exit successfully: `rustc --crate-name regex_syntax /root/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.4.1/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=2670ae5f089f9aeb -C extra-filename=-2670ae5f089f9aeb --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `arbitrary`.

Caused by:
  process didn't exit successfully: `rustc --crate-name arbitrary /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arbitrary-0.1.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=e68d1b475408f834 -C extra-filename=-e68d1b475408f834 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
error: Could not compile `serde`.

Caused by:
  process didn't exit successfully: `rustc --crate-name serde /root/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.15/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg feature="default" --cfg feature="std" -C metadata=677acf5414683fc0 -C extra-filename=-677acf5414683fc0 --out-dir /root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/root/sniffglue/fuzz/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/root/sniffglue/fuzz/target/debug/deps --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort` (signal: 6, SIGABRT: process abort signal)
error: could not build fuzz script: "cargo" "build" "--manifest-path" "/root/sniffglue/fuzz/Cargo.toml" "--verbose" "--bin" "read_packet" "--target" "x86_64-unknown-linux-gnu"
# 
```

**Comment by oyvindln** [comment]
I am having the same issue on Ubuntu 17.04.

**Comment by kpcyrd** [comment]
I've started getting this error on archlinux as well.

**Comment by sanmai-NL** [comment]
I can confirm @kpcyrd issue on Arch Linux.

**Comment by frewsxcv** [comment]
For anyone who's commented here, is it the case that cargo-fuzz used to work up until a certain version of rustc? i.e. did upgrading rustc cause cargo-fuzz breakage? If so, it'd be helpful to know which version of rustc

**Comment by sanmai-NL** [comment]
`rustc 1.22.0-nightly (b633341c4 2017-10-20)`

**Comment by oyvindln** [comment]
It's worked in the past for me, though the last time I tinkered with it seems to have been in may, so I don't really know when it broke.

**Comment by kpcyrd** [comment]
This one worked for me:
```
$ rustup run nightly rustc --version
rustc 1.22.0-nightly (417c73891 2017-10-05)
```

This one didn't:
```
$ rustup run nightly rustc --version
rustc 1.22.0-nightly (02a24dbdd 2017-10-13)
```

Note that the machines aren't 100% identical.

**Comment by hcpl** [comment]
By bisecting I found out that this works:
```
$ rustc +nightly-2017-10-08 --version
rustc 1.22.0-nightly (05f8ddc46 2017-10-07)
```
but this doesn't:
```
$ rustc +nightly-2017-10-09 --version
rustc 1.22.0-nightly (150b625a0 2017-10-08)
```
Since 2017-10-09 is the release date of 1.21 and the date when beta forked, I suspect this fact to be the root cause. Pinging @frewsxcv to confirm this.

**Comment by Manishearth** [comment]
With Rust nightly on Linux I get this reduced testcase:


```rust
pub fn add(x: u8, y: u8) -> u8 {
    x + y
}
```

```
$ rustc src/lib.rs  --crate-type lib -Zsanitizer=address
rustc: /checkout/src/llvm/include/llvm/ADT/StringRef.h:236: char llvm::StringRef::operator[](size_t) const: Assertion `Index < Length && "Invalid index!"' failed.
Aborted (core dumped)
```

We pass `-Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address -Cpanic=abort`, but the panic happens even without all of those flags.

**Comment by frewsxcv** [comment]
here's the issue upstream: https://github.com/rust-lang/rust/issues/45220

**Comment by bluss** [comment]
We can fuzz on the latest nightly again, due to llvm assertions being disabled now. So it hides a bug, unknown what the impact of that is (?)

**Comment by kpcyrd** [comment]
As @bluss noted, I think this is fixed.

**Comment by oyvindln** [comment]
It's not really fixed, it's just hidden as long as assertions are disabled.

**Comment by kpcyrd** [comment]
@oyvindln should I reopen the issue? My initial problem was that it didn't work at all. :)

**Comment by sanmai-NL** [comment]
@kpcyrd: I think: yes. Building LLVM with assertions enabled as before should be possible.

**Comment by frewsxcv** [comment]
This appears to be resolved upstream, try cargo-fuzz with the latest Rust nightly: https://github.com/rust-lang/rust/issues/45220

Let me know if anyone can still reproduce and I'll reopen this
